dist: trusty
sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then rustup update && rustup component add clippy-preview ; fi

script:
  - RUSTFLAGS="-D warnings" cargo build
  - RUSTFLAGS="-D warnings" cargo test
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then RUSTFLAGS="-D warnings" cargo clippy ; fi
