[package]
name = "aitch"
description = "A HTTP server toolkit, loosely based on Go's net/http."
license = "MIT"
version = "0.1.0"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]

[dependencies]
bytes = "0.4.8"
futures = "0.1"
http = "0.1"
hyper = "0.12"
serde = "1.0"
serde_json = "1.0"
